[package]
name = "toktrie"
version = "0.6.17"
edition = "2021"
license = "MIT"
description = "LLM Token Trie library"
repository = "https://github.com/guidance-ai/llguidance"

[lib]
name = "toktrie"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
anyhow = "1.0.95"
bytemuck = "1.21.0"
bytemuck_derive = "1.8.1"
hashbrown = "0.15.2"
